### ISSUE TITLE
驗證機制似乎壞掉了

### ISSUE THREAD

**Issue by yeefun** [readr-media/election-boards#69] opened 2019-10-24 08:24 UTC
我聽學勇說，一個看板若被驗證**錯**三次，內容就會改變。也就是說，假設今天一個看板的原始候選人是「蔡英文」，但有三次驗證它為「蘇貞昌」，那這個看板的候選人就會變成「蘇貞昌」。

不過現在這個機制似乎無法啟動，我針對這個[看板](http://dev.readr.tw/project/election-boards/api/verify/board/35)驗證了 8 次，有 4 次將候選人「原住民1」驗證為「蔡英文」，但內容並沒更改，請幫我看一下驗證機制是否出了問題。

**Comment by ichiaohsu** [comment] 2019-10-24 10:28
As usual, please provide the example you used. I could not locate the root cause simply based on your description. Thanks.

@yeefun

**Comment by yeefun** [comment] 2019-10-24 13:21
我在第二段有寫道我測試的 api：http://dev.readr.tw/project/election-boards/api/verify/board/35

它的 board id 是 35，candidates id 是 98393。

從`verified_amount`這個欄位可以看到我驗證了 8 次。沒記錯的話，前 4 次是改標語，後 4 次是改候選人名。前 4 次我忘記我改成什麼標語，但都是同一句；後 4 次我則都改成「蔡英文」。

@ichiaohsu

**Comment by ichiaohsu** [comment] 2019-10-25 04:27
It's not broken. According to the code, it's by design, and it's not as simple as you described. 

This mechanism runs in following order:
1.  When doing single check, server will try to find the max `headcount`, which means the number of candidates most people think appearing in this board. If the max number is `None`, which means most people do not fill in the `headcount`, then server will use the answer when people upload this board. 

2. server will pull out the verifying history, to see who are the most frequent verified candidates to this board, and select corresponding answer according to step 1. When they are verified equally, it will be listed in descending order in candidates `id`.

3. Overwrites the board's connection with candidates with the answer in step 2

In your case, when you upload this board, you did denote the `headcount` to be `1`. But in the following verification, you leave the `headcount` blank. So the server will act like this:

1. Most people said there is only 1 candidate
2. Select **1** candidates from verification history, which is `98393` and `98392`. They are both verified 4 times, so candidates with greater `id` will be list first. In this case, `98393`.
3. Modify the board's candidates. Since it's already `98393`, it seems nothing changed to you.

So it's not a bug. The root cause to this is: They are both verified 4 times. 

@yeefun

**Comment by yeefun** [comment] 2019-10-25 06:37
因為這次的版本沒有 `headcount` 這個欄位，所以每次都會傳 `None`。我把它預設為 `1` 後，驗證修改機制就可以 work 了，感謝！

**Comment by ichiaohsu** [comment] 2019-10-25 09:23
So it's not an issue now, isn't it? Could we close this?

**Closed** 2019-10-25 09:25 UTC
Labels: wontfix
